---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: 包含多項新功能與增強功能。Cloud Volumes ONTAP 
---
= 更新功能Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
包含多項新功能與增強功能。Cloud Volumes ONTAP

最新版的BlueXP也會提供其他功能和增強功能。請參閱 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXP版本說明"^] 以取得詳細資料。



== 不再支援的c4、m4和r4執行個體（2022年10月28日）

在AWS中Cloud Volumes ONTAP 、不再支援C4、M4和R4 EC2執行個體類型。如果現有系統執行的是c4、m4或r4執行個體類型、則必須變更為c5、m5或R5執行個體系列中的執行個體類型。

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["瞭解如何變更EC2執行個體類型Cloud Volumes ONTAP 以供使用"^]。

請參閱 link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp支援"^] 以深入瞭解這些執行個體類型的終止可用度和支援。



== 9.8 GA（2021年1月5日）

目前已推出《通用版本Cloud Volumes ONTAP 》（GA）發行版的《更新版本》（英文）。GA版本包含錯誤修正。BlueXP會提示您將現有的9.8 RC1和9.7系統升級至此版本。



== Connector 3.9.2的變更（2021年1月4日）

BlueXP Connector的3.9.2版本包含Cloud Volumes ONTAP 多項功能增強功能、包括支援AWS outs、Google Cloud中的較大磁碟等。

前往 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXP版本說明"^] 如需3.9.2版本的詳細資訊、



== E48s_v3現在支援HA配對（2020年12月21日）

E48s_v3 VM類型現在可在Cloud Volumes ONTAP Microsoft Azure中搭配使用支援的功能。



== 支援的EC2執行個體（2020年12月11日）

從9.8版開始、新Cloud Volumes ONTAP 版的功能不支援新版的C4、M4和R4 EC2執行個體類型。也不支援將現有的9.8系統變更為其中一種執行個體類型。

如果您現有Cloud Volumes ONTAP 的執行於c4、m4或r4執行個體類型上的版本為更新版本、您仍可升級至9.8。



== 9.8 RC1更新（2020年11月12日）

與單一節點系統類似、現在當您使用c5、M5或R5執行個體類型時、BlueXP會將核心磁碟配置給AWS中新的9.8 HA配對部署。核心磁碟可擴充在支援的執行個體類型之間切換的能力、強化系統在發生問題時收集核心檔案的能力、並提供未來支援較大型執行個體類型的能力。

核心磁碟是通用SSD（gp2）、配備540 GiB。


NOTE: 新增此核心磁碟後、使用這些執行個體類型的系統現在可減少一張資料磁碟。 link:reference-limits-aws.html["深入瞭解AWS的儲存限制"]。



== 9.8 RC1（2020年11月8日）

目前AWS、Azure和Google Cloud Platform均提供此功能。Cloud Volumes ONTAPAzure目前僅提供9.8 RC1升級。

除了所介紹的功能之外 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["部分9.8 ONTAP"^]、Cloud Volumes ONTAP 本版的《》包含下列內容：

* <<Google Cloud的高可用度配對>>
* <<Azure NIC分離事件與維護事件的修正>>
* <<AWS和Azure中的HA配對可提供高速寫入速度>>
* <<在AWS中最多支援24個儲存VM>>
* <<AWS單一節點系統的核心磁碟>>




=== Google Cloud的高可用度配對

目前Google Cloud提供高可用度（HA）配對。Cloud Volumes ONTAP

HA配對可在雲端環境發生故障時、提供企業級的可靠性和持續運作。與Cloud Volumes ONTAP AWS中的一樣、Google Cloud中的HA配對包含兩Cloud Volumes ONTAP 個彼此同步鏡射資料的支援節點、以及一個提供通訊通道來協助儲存接管和恢復的中介執行個體。

檢視 link:reference-configs-gcp.html["支援的組態"] 和 link:reference-limits-gcp.html["儲存限制"]。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-google-cloud.html["深入瞭解Google Cloud的HA配對"^]。



=== Azure NIC分離事件與維護事件的修正

此版本提供多項改良功能、可讓Cloud Volumes ONTAP 您瞭解如何處理Azure凍結事件、Azure NIC分離事件及其他Azure維護活動（例如、虛擬功能撤銷）。此版本可提供更多容錯能力、並能更妥善地處理Azure事件、降低服務中斷或叢集降級的可能性。Cloud Volumes ONTAP



=== AWS和Azure中的HA配對可提供高速寫入速度

使用特定執行個體或VM類型時、支援AWS和Azure中的HA配對高速寫入。Cloud Volumes ONTAP如果您的工作負載需要快速寫入效能、而且在非計畫性的系統中斷時、您可以承受資料遺失的風險、那麼高速寫入速度是很好的選擇。

在您選擇寫入速度之前、您應該先瞭解一般與高設定之間的差異、以及使用高速寫入速度時的風險與建議。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["深入瞭解"^]。



=== 在AWS中最多支援24個儲存VM

當您使用c5、M5或R5執行個體類型、並自帶授權時、AWS最多可支援24個儲存VM。Cloud Volumes ONTAP在這24個儲存VM中、最多可設定12個用於災難恢復（DR）。

此限制可能較低、視您使用的EC2執行個體類型而定。

在預設情況Cloud Volumes ONTAP 下、除了第一個隨附的儲存VM之外、每個額外的_data-Serving儲存VM都需要附加授權。請聯絡您的客戶團隊以取得 SVM 附加授權。

您設定用於災難恢復（DR）的儲存VM不需要附加授權（免費）、但它們確實會根據儲存VM的限制而計算。

link:reference-limits-aws.html["深入瞭解儲存VM限制"]。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-aws.html["瞭解如何在Cloud Volumes ONTAP AWS中建立資料服務儲存VM以供其使用"^]。



=== AWS單一節點系統的核心磁碟

現在、當您使用c5、M5或R5執行個體類型時、BlueXP會將核心磁碟配置給AWS中新的9.8個單一節點部署。核心磁碟可擴充在支援的執行個體類型之間切換的能力、強化系統在發生問題時收集核心檔案的能力、並提供未來支援較大型執行個體類型的能力。

核心磁碟是通用SSD（gp2）、配備540 GiB。


NOTE: 新增此核心磁碟後、現在使用這些執行個體類型的單一節點系統可支援少一張資料磁碟。 link:reference-limits-aws.html["深入瞭解AWS的儲存限制"]。



== 所需版本的BlueXP Connector

BlueXP Connector必須執行3.9.0版或更新版本、才能部署新Cloud Volumes ONTAP 的版本號、並將現有系統升級至9.8版。



== 升級附註

* 必須從BlueXP完成升級。Cloud Volumes ONTAP您不應 Cloud Volumes ONTAP 使用 System Manager 或 CLI 來升級功能。這樣做可能會影響系統穩定性。
* 您可以從Cloud Volumes ONTAP 9.7版升級至版本的版本更新至版本不含更新的版本。BlueXP會提示您將現有Cloud Volumes ONTAP 的更新版升級至9.8版。
+
http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["瞭解如何在BlueXP通知您時進行升級"^]。

* 單一節點系統的升級可讓系統離線長達25分鐘、在此期間I/O會中斷。
* 升級 HA 配對不中斷營運、而且 I/O 不中斷。在此不中斷營運的升級程序中、會同時升級每個節點、以繼續為用戶端提供 I/O 服務。

